[package]
name = "multi-skill"
version = "0.1.2"
authors = ["Aram Ebtekar <aramebtech@gmail.com>"]
edition = "2018"

description = "Skill estimation systems for multiplayer competitions"
repository = "https://github.com/EbTech/Elo-MMR"
readme = "../README.md"
keywords = ["skill", "rating", "estimation", "competition", "bayesian"]
categories = ["algorithms", "mathematics", "game-development"]
license = "MIT"

[dependencies]
rayon = "1.5"
reqwest = { version = "0.11.2", default-features = false, features = ["blocking", "json", "rustls-tls-native-roots"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
statrs = "0.13"
overload = "0.1.1"
csv = "1.1"
select = "0.6.0-alpha"
superslice = "1.0"
tracing = "0.1.25"
tracing-subscriber = "0.2.17"
smallvec = { version = "1.6", features = ["union"] }
rand = "0.8.3"
json5 = "0.3.0"
f128 = "0.2.9"
num-traits = "0.2.14"
itertools = "0.10.0"
chrono = "0.4.19"

[[bin]]
name = "rate"

[[bin]]
name = "eval"

[[bin]]
name = "hparam_search"

[[bin]]
name = "dance"

[[bin]]
name = "adversary"

[[bin]]
name = "summarize_dataset"
