name: Instant README update

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch: 

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Dependency
        run: |
          cd $GITHUB_WORKSPACE
          git submodule update --init --recursive
          ls -ahl $GITHUB_WORKSPACE
          sudo apt-get install libssl-dev pkg-config

      - name: Boilerplate for action-rs/cargo@v1
        run: |
          mkdir ../cache/
          mkdir ../cache/TFM/
          mkdir ../data/

      - name: Converting log format
        run: |
          python utils/ELOMMR.py logs/*.log
          mv logs/S*/* ../cache/TFM/

      - name: Run Elo-MMR calculator
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: --manifest-path ./Elo-MMR/multi-skill/Cargo.toml --release --bin rate mmr TFM 
      
      - name: Checkout result
        run: |
          cat ../data/TFM/all_players.csv

      - name: Reflect to READMD.md
        run: |
          cat README.template > README.md
          echo "# Standings - S2" >> README.md
          echo "\`\`\`csv" >> README.md
          sed -i 's/display_rating/rating/g; s/num_contests/games/g; s/handle/name/g;' ../data/TFM/all_players.csv
          awk -F, -v OFS='\t' '{ print $1, $2, $5, $10 }' ../data/TFM/all_players.csv >> README.md
          echo "\`\`\`" >> README.md

      - name: Add & Commit
        uses: EndBug/add-and-commit@v7.2.1
        with:
          add: './README.md'
          author_name: PngWnA
          author_email: gnu@korea.ac.kr
          branch: main
          cwd: '.'
          default_author: github_actor
          message: 'Instant README update'
          pull_strategy: '--no-rebase'
          push: true